### ISSUE TITLE
Add NestedLoop pattern problems in Java

### ISSUE THREAD

**Issue by DevDatir** [DhanushNehru/Hacktoberfest2024#147]
Hey,
I would really like to contribute to this repo @DhanushNehru.
Please assign me this issue under hacktoberfest tag!

**Comment by tri0n0** [comment]
Hi @DhanushNehru, I'd love to contribute to this issue. I'm familiar with Java and excited to help with the nested loop pattern problems. Let me know if there are any guidelines to follow. Looking forward to contributing!

**Comment by DevDatir** [comment]
Hey, please review this PR - #165

**Comment by anu098jaiswal** [comment]
i would love to do these please assign
