### ISSUE TITLE
Queue Implementation using a Linked List using Python

### ISSUE THREAD

**Issue by thechiranjeevvyas** [DhanushNehru/Hacktoberfest2024#158]
hi @DhanushNehru ,
I would like to implement python solution for Queue Implementation using a Linked List using Python.
***
Please assign this issue to me under Hacktoberfest-2024. Thank you!

**Comment by DevendraJaiswal074** [comment]
Hii, @thechiranjeevvyas 
I'm passionate about problem-solving and eager to contribute. I'd love the opportunity to tackle this issue. Could you assign me?

**Comment by thechiranjeevvyas** [comment]
> Hii, @thechiranjeevvyas I'm passionate about problem-solving and eager to contribute. I'd love the opportunity to tackle this issue. Could you assign me?

even i am not assigned for this ask @DhanushNehru
