### ISSUE TITLE
Number Guessing Game

### ISSUE THREAD

**Issue by Mudassir97** [DhanushNehru/Hacktoberfest2024#168]
kindly assign to me

**Comment by LakshmiSrikumar** [comment]
@DhanushNehru @Mudassir97 Kindly add hacktober label because the repository is not taken in consideration

**Comment by DhanushNehru** [comment]
Hi @LakshmiSrikumar  this is just a template repo to fork and raise a PR

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31)  and join discord for more discussions
