### ISSUE TITLE
Proposal to add most asked DSA problem

### ISSUE THREAD

**Issue by Sar-taj107** [DhanushNehru/Hacktoberfest2024#22]
I would like to contribute in this repo by adding few most common asked DSA coding problems with complete solution in java, if you ok with my idea, please assign me this task with hacktoberfest 2024 tag.
Thank you!

**Comment by Deepikakolli4** [comment]
I’m excited to contribute to this repository by adding some of the most commonly asked DSA coding problems, complete with detailed Java solutions. If this sounds good to you, could you assign me this task and tag it with Hacktoberfest 2024? I appreciate your support!

**Comment by Mannxxx** [comment]
I would like to contribute. please assign me as well.

**Comment by Aastha7078** [comment]
I am interested in working on this issue. please assign it to me

**Comment by ishika1880** [comment]
I'd like to contribute to the repository by adding solution to commonly asked DSA problem. Please assign me this issue

**Comment by DhanushNehru** [comment]
Here on no need assignment, people can directly contribute 

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31) and for further queries join discord for more discussions
