### ISSUE TITLE
Java Stream API Coding Interview Question

### ISSUE THREAD

**Issue by Spardha-hash** [DhanushNehru/Hacktoberfest2024#26]
Hi @DhanushNehru ,
I want to add the solution of the below java interview coding question using stream api functions.

Given a String, find the first repeated character in it using Stream functions?

Input : 
String input = "Java Articles are Awesome";
Output = a

@DhanushNehru Please assign this issue to me.

**Comment by Spardha-hash** [comment]
Thanks @DhanushNehru , I am working on this issue.

**Comment by Playmaker12345** [comment]
Hello, can I help the project as much as possible?
