### ISSUE TITLE
Rotate Array in java

### ISSUE THREAD

**Issue by Sofiyan-coder** [DhanushNehru/Hacktoberfest2024#283]
## Given an integer array nums, rotate the array to the right by k steps, where k is non-negative.

 <br>

Example 1:
<br>
Input: nums = [1,2,3,4,5,6,7], k = 3
<br>
Output: [5,6,7,1,2,3,4]
<br>
Explanation:
<br>
rotate 1 steps to the right: [7,1,2,3,4,5,6]
<br>
rotate 2 steps to the right: [6,7,1,2,3,4,5]
<br>
rotate 3 steps to the right: [5,6,7,1,2,3,4]
<br>
Example 2:
<br>
Input: nums = [-1,-100,3,99], k = 2
<br>
Output: [3,99,-1,-100] <br>
Explanation: <br>
rotate 1 steps to the right: [99,-1,-100,3]<br>
rotate 2 steps to the right: [3,99,-1,-100]<br>
 
# [Leetcode Problem link](https://leetcode.com/problems/rotate-array/description)

**Comment by Sofiyan-coder** [comment]
@DhanushNehru assign me this I would like to work on it. To start my open source contribution

**Comment by Laxmijai** [comment]
#Dhanush nehru please assign me this task

**Comment by DhanushNehru** [comment]
Hi  this is just a template repo to fork and raise a PR

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31)  and join discord for more discussions
