### ISSUE TITLE
Proposal to add the directory which contains content based on the topics of Python 

### ISSUE THREAD

**Issue by Yogeshkarma** [DhanushNehru/Hacktoberfest2024#32]
Proposal to add the directory/Folder in the repo which will contains the insights of the topics of Python in Markdown File  Format
The topics like universal Functions, Decorators etcs

**Comment by Shrutika-TechSavvy** [comment]
Hi  @Yogeshkarma , I would be happy to work on this issue. I can create a new directory in the repo that includes detailed Markdown files on Python topics as required. Please let me know if there are any topics you'd like covered or any specific structure you'd prefer for the content.
Looking forward to contributing!

**Comment by Yogeshkarma** [comment]
@DhanushNehru It is shown under the all the PR in Hacktoberfest that this repo is excluded from the event

**Comment by Yogeshkarma** [comment]
@DhanushNehru 
![image](https://github.com/user-attachments/assets/8a57fbc0-41ae-48bd-954b-4ba907aadd7a)

**Comment by DhanushNehru** [comment]
Hi @Yogeshkarma  this is just a template repo to fork and raise a PR

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31)  and join discord for more discussions
