### ISSUE TITLE
Proposal to add Vigenère Cipher program in Java.

### ISSUE THREAD

**Issue by Immanuel-Anthony** [DhanushNehru/Hacktoberfest2024#36]
Proposal : 

I would like to add a Vigenère Cipher program in Java to =>
- Encrypt Data
- Decrypt Data 

Thank you!

**Comment by Immanuel-Anthony** [comment]
Hey, 
Just wanted to know if assigning the 'hacktoberfest' label is mandatory or not, so that this PR counts towards my hacktober PRs.
If yes, Could you kindly assign the hacktoberfest label to this.

Thank you!

**Comment by DhanushNehru** [comment]
Hi @Immanuel-Anthony  this is just a template repo to fork and raise a PR

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31) and for further queries join discord for more discussions

**Comment by Immanuel-Anthony** [comment]
Got it!
Thank you for the label and the repo link :)
