### ISSUE TITLE
Proposal : Adding an implementation of the Rat in a Maze Problem in C++.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [DhanushNehru/Hacktoberfest2024#61]
Consider a rat placed at (0, 0) in a square matrix of order N * N. It has to reach the destination at (N - 1, N - 1). Find all possible paths that the rat can take to reach from source to destination. The directions in which the rat can move are 'U'(up), 'D'(down), 'L' (left), 'R' (right). Value 0 at a cell in the matrix represents that it is blocked and the rat cannot move to it while value 1 at a cell in the matrix represents that rat can travel through it.

**What I’d Like to Do:**

- Implement the algorithm to find all possible paths for the rat to traverse from the start point to the destination in a maze represented as a 2D grid.
- Provide a method to display the paths taken by the rat.
- Write test cases to verify the implementation and ensure all edge cases are covered.

**Comment by AbhijitMotekar99** [comment]
Hey @DhanushNehru 
Please give the label of hacktoberfest and hacktoberfest2024.

**Comment by DhanushNehru** [comment]
Hi @AbhijitMotekar99 this is just a template repo to fork and raise a PR

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31)  and join discord for more discussions
