### ISSUE TITLE
Proposal : Sudoku Solver

### ISSUE THREAD

**Issue by AbhijitMotekar99** [DhanushNehru/Hacktoberfest2024#63]
Problem Statement:

Given a 9x9 incomplete sudoku, solve it such that it becomes valid sudoku. Valid sudoku has the following properties.

         1. All the rows should be filled with numbers(1 - 9) exactly once.

         2. All the columns should be filled with numbers(1 - 9) exactly once.

         3. Each 3x3 submatrix should be filled with numbers(1 - 9) exactly once.

![Screenshot 2024-10-02 192115](https://github.com/user-attachments/assets/85cba5c3-a39c-40df-b6c1-44077a32f38e)

**Comment by AbhijitMotekar99** [comment]
Hey @DhanushNehru 
Please give the label of hacktoberfest and hacktoberfest2024.

**Comment by arnav0805** [comment]
Hey @DhanushNehru 
Please assign me the problem and label it as hacktoberfest

**Comment by AbhijitMotekar99** [comment]
This Repository is excluded try to contribute in another Repository

**Comment by DhanushNehru** [comment]
Hi @AbhijitMotekar99 @arnav0805  this is just a template repo to fork and raise a PR

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31)  and join discord for more discussions
