### ISSUE TITLE
Proposal:  To Implement Robin-Karp String Matching Algorithm in C++  

### ISSUE THREAD

**Issue by Ankitmohanty2** [DhanushNehru/Hacktoberfest2024#76]
I would like to contribute to this repository by implementing the Rabin-Karp algorithm in C++ as part of Hacktoberfest 2024. This algorithm uses a hashing technique for efficiently finding the occurrence of a pattern in a text, which is useful for multiple pattern matching problems.

**Comment by Ankitmohanty2** [comment]
added will u please add the label of hacktoberfest2024

**Comment by DhanushNehru** [comment]
Hi @Ankitmohanty2  this is just a template repo to fork and raise a PR

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31)  and join discord for more discussions

**Comment by Ankitmohanty2** [comment]
Done
