### ISSUE TITLE
Add C++ File with Sorting Algorithms

### ISSUE THREAD

**Issue by KartikMouli** [DhanushNehru/Hacktoberfest2024#88]
Hi @DhanushNehru, I’d like to contribute a C++ file with 10 sorting algorithms, as the project currently lacks a C++ implementation.

The sorting algorithms I’ll include are:
Bubble Sort
Selection Sort
Insertion Sort
Merge Sort
Quick Sort
Heap Sort
Radix Sort
Counting Sort
Shell Sort
Bucket Sort

Kindly assign this issue to me and add the Hacktoberfest label.

**Comment by uddipbisht** [comment]
can you assign this to me under hacktoberfest 2024 need contribution bro

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign me this work under label hacktoberfest.
Thank You!

**Comment by vikassahu1** [comment]
created pull request

**Comment by KartikMouli** [comment]
completed !
